(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.thermometer = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.5,1,1).p("AJ1bvQAAEEi4C4Qi4C5kFAAQkEAAi4i5Qi4i4AAkEQAAkFC4i4QBHhHBSgrMAAAg0pQAAhnBJhKQBJhJBoAAIBTAAQBoAABJBJQBJBKAABnMAAAA0pQBSArBHBHQC4C4AAEFg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["rgba(255,255,255,0)","rgba(191,191,191,0.298)"],[0,1],30.7,-33.4,0,0.1,-2.7,61.4).s().p("Am8GZQi4i3AAkEQAAkFC4i4QBHhGBSgsQApBgBUA1QBPAxBdABQBegBBMgyQBSg1AihfQBSAsBHBGQC4C4AAEFQAAEEi4C3Qi5C5kEAAQkEAAi4i5g");
	this.shape_1.setTransform(0,181);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(149,149,149,0.498)","rgba(220,220,220,0.161)","rgba(240,240,240,0.067)","rgba(255,255,255,0)","rgba(231,231,231,0.114)","rgba(208,208,208,0.22)","rgba(151,151,151,0.49)"],[0,0.247,0.51,0.737,0.851,0.941,1],-29.2,0,29.2,0).s().p("AimdEQhUg2gphgMAAAg0oQAAhnBJhKQBKhJBnAAIBTAAQBnAABKBJQBJBKAABnMAAAA0oQgiBfhSA2QhMAyheAAQhdAAhPgxg");
	this.shape_2.setTransform(0,-49.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.thermometer, new cjs.Rectangle(-63.9,-241.3,127.8,482.70000000000005), null);


(lib.Symbol2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#0099CC").ss(0.5,1,1).p("AkqllQEMA1FJg1QBkAAAABkQgyFvAyCEQAABkhkAAQjLAgmKggQhkAAAAhkQAem0geg/QAAhkBkAAg");
	this.shape.setTransform(39.875,35.7875);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(149,234,255,0.4)","rgba(115,171,227,0.647)"],[0,1],-39.8,-0.7,39.9,-0.7).s().p("AkqFWQhkAAAAhkQAem0geg/QAAhkBkAAQEMA1FJg1QBkAAAABkQgyFvAyCEQAABkhkAAQhmAQiVAAQiUAAjGgQg");
	this.shape_1.setTransform(39.875,35.7875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-1,-1,81.8,73.6), null);


(lib.dragger = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(5,1,1).p("AACAAQAAhhBEhFQBFhEBiAAQBiAABEBEQBFBFAABhQAABihFBEQhEBFhiAAQhiAAhFhFQhEhEAAhigAnXAAIHZAA");
	this.shape.setTransform(47.2,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#999999").s().p("AilCmQhFhFAAhhQAAhgBFhGQBFhEBgAAQBhAABFBEQBFBGAABgQAABhhFBFQhFBFhhAAQhgAAhFhFg");
	this.shape_1.setTransform(70.9,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.dragger, new cjs.Rectangle(-2.5,-26,99.4,52), null);


(lib.blocker = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ai1VpMAAAgrRIFrAAMAAAArRg");
	this.shape.setTransform(0,-138.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.blocker, new cjs.Rectangle(-18.2,-277,36.4,277), null);


(lib.ice_melts = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		this.typ = 'i';
	}
	this.frame_2 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2).call(this.frame_2).wait(1));

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.408)").s().p("AlkGJQgFgBgCgGQgCgGACgFQADgHANgIQAtgeAzgnQAmgdAYgWQAkgiAzg7IBThfQAYgbAjggQAxgvApgNQAKgDAFABQAKABABAIQADALgVAIQglAOglAgQgXAVgnArIhYBkQg5BAgaAYQgkAig7ArQghAYgtAfQgHAFgFAAIgCgBgAFgE+QgGgBgDgFQgBgEAAgGQAAgIACgEIAGgGIAFgIQAFgHAAgEIABgOQAAgHAEgKIAGgRQADgJgBgOIgBgMQgCgLAAgDQABgHAGgCQAGgDAGADQAGADACAIQADAHAAALQAAAPgCAPIgDAPIgGANIgBAMIgBAMQgBAFgHAOIgLATQgDAGgDACQgDADgEAAIgDgBgAmLChQgFgGABgGQACgLAPgJQAQgIAHgGQAEgDAGgHIAIgNQAFgGAJgIIAPgPQAKgKAMgUIAUgfIAUgZIAVgZIAmgyQAWgfATgQIASgOQALgJAFgHQAKgMAFgEQAFgDAFAAQAGAAAEAEQAIAKgPAPQgIAJgQANIgYAWQgSARgXAfIgnAzIgSAWIgSAWIgMAVQgHANgFAHQgHAIgPAPIgVAXIgKANQgFAIgGAEQgEAEgLAGQgKAFgEAEIgHAIQgEAEgEABIgCAAQgFAAgEgFgAFRgRQgGgCgDgFQgEgIABgPQABgbAMg2QADgJAAgIIACgUIAFgTQADgLAAgWIAAgqIgBgVIgDgNQAAgIAEgEQAFgEAHABQAGACAEAFQAEAGABASIAAA0QABAdgEAQIgGATIgCASQgBAOgEASIgHAiQgEAUACAPQABATgGAFQgDACgDAAIgFgBgABpkqQgFgCgEgFQgDgFACgFQADgJARgCIAagGIArgMIApgMQAXgIARgJQAcgQAIgCQALgDAHADQAEABADAEQADAFgBAEQgCAIgMADIgRAFIgNAKQgFADgHADIgrAQIhmAdQgJADgHAAIgGgBgAjYlQIgUgFIgUgEQgJgBgDgCIgDgDIgFAAIgbAAIgIABIgKADQgEABgEgDQgEgDgBgEQgEgJAIgHQAGgGATAAIAhAAQAJAAADADIAEADQAQAAAeAKQAQAEAagBIBLgDQALgBAFAEQAFADABAGQAAAHgEAEQgFAEgNABIgwACIgZAAQggAAgSgEg");
	this.shape.setTransform(53.8159,43.315);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.408)").s().p("AhyCGQg8gBhMgFIiIgKIhygJQgPgBgBgIQgBgGAIgEQAHgDAIACQCdAVDFADQB6ABDpgHQA2gCAWgGQASgFAjgMQANgEAbgGQAagGANgEQAvgQAUgcQAJgOgCgIQgCgLgFgJQgGgKgNgLQgNgMgmgWQgmgXgWgHQgRgFgCgBQgEgDgCgFQgCgFACgFQAqgCAkAcQAjAbAGACQAGABAMAKQANAKALAPQAMAOAGAMQAHAQgKAUQgIARgSANQgWASgiAMQgUAIgpAMQg7ARgfAFQgYAEggABIg3ACIhyADQhQACg/AAIgYAAg");
	this.shape_1.setTransform(88.8739,69.2474);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},2).wait(1));

	// Layer_1
	this.instance = new lib.Symbol2();
	this.instance.setTransform(39.9,50.95,1,1,0,0,0,39.9,35.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(2));

	// Layer_2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#0099CC").ss(0.5,1,1).p("AjFmhQELA1FKg1QBkAAAABkQgyFvAyCEQAAA4gfAZQgBAAgCABQgEAEgFACQhbBRiRBDQAkgYAAg8QgGgRgFgVQggiNArlAQAAhkhkAAQjsAmjNgRQhQgGhLgPQgkAAgYANQBjhNCIhGQAZgSAqAAg");
	this.shape_2.setTransform(54.0375,41.775);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(149,234,255,0.4)","rgba(115,171,227,0.647)"],[0,1],-49.9,0,50,0).s().p("AEBFOQgGgRgFgVQggiNArlAQAAhkhkAAQjsAmjNgRQhQgGhLgPQgkAAgYANQBjhNCIhGQAZgSAqAAQELA1FKg1QBkAAAABkQgyFvAyCEQAAA4gfAYIgDACIgJAGQhbBRiRBDQAkgYAAg8g");
	this.shape_3.setTransform(54.0375,41.775);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#0099CC").ss(0.5,1,1).p("ACyGiQjKAfmLgfQhkAAAAhkQAem1geg+QAAhIA0gUQgGACgFADQBjhNCHhGQADgCADgBIA1gOQAEgBAEAAQELA1FKg1QBkAAAABkQgxFvAxCEQAAACAAACQAAABAAABQAAABAAABQAAABAAABQAAAEAAADQgBABAAABQAAACAAABQAAABAAAAQAAABAAABIgYAzQgDACgDADQgBAAgBABIAAAAQgBABgBAAQgEADgEACQhbBRiQBDQACgBACgCQgZATgrAAg");
	this.shape_4.setTransform(52,43.3625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(149,234,255,0.4)","rgba(115,171,227,0.647)"],[0,1],-52,6.8,27.8,6.8).s().p("AmjGiQhkAAAAhkQAem1geg+QAAhIA0gUIgLAFQBjhNCHhGIAGgDIA1gOIAJgBQEKA1FKg1QBkAAAABkQgyFvAyCEIAAAEIAAACIAAACIAAACIgBAHIAAACIAAADIAAABIAAACIgYAzIgGAFIgCABIAAAAIgCABIgIAFQhbBRiQBDIAEgDQgZATgrAAQhmAQiUAAQiWAAjFgQg");
	this.shape_5.setTransform(52,43.3625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#0099CC").ss(0.5,1,1).p("ANygOQB4BnjWBVQjWBWpNgVQpOgVi0hWQi0hWA1hEQA0hFEDhFQEDhFFogLQFogMDABDQDABDB4Bog");
	this.shape_6.setTransform(56.0732,63.5728);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(149,234,255,0.4)","rgba(115,171,227,0.647)"],[0,1],-92.5,0,92.6,0).s().p("AgPDvQpOgVi0hWQi0hWA1hEQA0hFEDhFQEDhFFogLQFogMDABDQDABDB4BoQB4BnjWBVQisBFmeAAQhmAAhzgEg");
	this.shape_7.setTransform(56.0732,63.5728);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

	// Layer_5
	this.instance_1 = new lib.Symbol2();
	this.instance_1.setTransform(64.15,35.8,1,1,0,0,0,39.9,35.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},1).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.4,-1,187,89.9);


// stage content:
(lib.isotopes_melt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		this.melt = function(num) {
			if(this['i_'+num].currentFrame == 0) {
				this['i_'+num].play();
			}
		}
		this.pm = function(e) {
			console.log(e.stageY);
			if(this.y > e.stageY && this.y > 130) {
				this.y = this.parent.blc.y = e.stageY;
			}
			if(e.stageY < 348) {
				this.parent.melt(0);
			}
			if(e.stageY < 274) {
				this.parent.melt(1);
			}
			if(e.stageY < 222) {
				this.parent.melt(2);
			}
		}
		this.md = function(e) {
			console.log(e.stageY,this.y);
			this.on("pressmove",this.parent.pm.bind(this));
		}
		this.drg.on("mousedown",this.md.bind(this.drg));
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgQASQgEgEAAgOQAAgNAEgEQAFgFAMAAQALAAAFAEQAEAFAAANQAAANgEAFQgFAFgMAAQgLAAgFgFg");
	this.shape.setTransform(785.55,53.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgiBfIgIAAIgFgBIgDgCIAAgDIAAiuIAAgDQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAEgBIAHAAIAIAAIAEABIACACIABADIAAAZQAHgKAGgHQAHgHAEgDQAGgEAGgCIALgBIAGAAIAGABIAHACIAEACIABACIABACIAAAEIAAAHIAAAHIgBAFIgBADIgDAAIgDAAIgFgCIgHgCIgHgBQgFAAgFACQgFACgFAFIgKAMIgMASIAAByIgBADIgCACIgFABIgIAAg");
	this.shape_1.setTransform(778.675,46.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgeBaQgQgFgLgNQgLgLgGgSQgGgSAAgYQAAgWAGgRQAGgTALgNQALgMAQgHQAPgGASgBQAVAAAPAHQAOAHAJALQAKALAFAPQAEAQAAARIAAAFQAAAHgEADQgDAEgFAAIhzAAQAAAOACAMQAEAMAGAIQAHAJALAEQALAEAPABQANAAAKgCIARgFIALgEIAHgDIADABIABACIABAEIAAAGIAAAEIAAAEIgBACIgCACIgHAEQgEACgJACIgUAFQgKABgNABQgUAAgRgHgAgShCQgJAEgHAIQgGAHgDALQgDAKAAAKIBeAAQABgagMgOQgMgPgXAAQgLABgJAEg");
	this.shape_2.setTransform(760.55,46.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AABBzQgIgEgGgHQgHgHgCgLQgEgMAAgPIAAhmIgYAAQgDAAgCgDQgCgDABgHIAAgGIABgEIACgDIADAAIAYAAIAAgqIABgDIADgCIAEgBIAIgBIAIABIAFABIACACIABADIAAAqIAtAAIACAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIACAEIABAGQAAAHgDADQgBADgDAAIgtAAIAABhQAAASAFAKQAFAJAPAAIAIgBIAFgCIAGgBIADgBIACAAIABACIABAEIABAFIgBAJIgDAFIgEADIgIADIgIABIgJABQgOAAgKgEg");
	this.shape_3.setTransform(744.1,44.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgjBdQgMgDgHgIQgIgGgFgKQgEgKAAgNQAAgOAGgMQAGgKALgHQALgHARgDQAQgEAUAAIAYAAIAAgOQAAgKgCgIQgCgHgFgGQgFgFgHgCQgIgEgLAAQgLAAgJAEQgKADgHADIgMAGQgFADgCAAIgDgBIgCgCIgBgEIgBgFIABgIQABgDACgDIAJgFIAPgHIATgEQAKgDAJAAQATAAANAFQANAEAIAIQAJAJADAMQAEANAAAQIAAB2QAAAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgEABIgIABIgIgBIgEgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIAAgSQgLAMgOAHQgPAGgOABQgOgBgLgDgAgKAKQgJACgHAFQgGAFgDAFQgDAHAAAIQAAAOAJAHQAIAJAQgBQALAAALgGQALgHAMgNIAAglIgcAAQgMAAgKACg");
	this.shape_4.setTransform(727.925,46.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AA6BeIgKAAIgHgCIgEgCIgBgDIgkh/IgBgBIAAABIgiB/IgCADIgEADIgGABIgKAAIgKAAIgGgCIgEgCIgCgDIgzimIgCgFIAAgDIABgDIADgCIAFgBIAHAAIAJAAIAFABIADACIABADIAqCQIABACIAAgCIAniQIABgDIADgCIAFgBIAHAAIAHAAIAFABIADACIABADIAqCQIAAACIAAgCIAqiQIABgDIADgCIAFgBIAIAAIAIAAIAFABIACACIABADIgBADIgBAFIg0CmIgCADIgDADIgHABIgJAAg");
	this.shape_5.setTransform(705.075,46.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgLCJIgIAAIgEgBIgEgCIAAgDIAAiZIgZAAQgDAAgBgDQgCgDAAgHIAAgGIACgEIABgDIADAAIAZAAIAAgTQAAgSAEgNQACgNAIgJQAGgIALgEQAKgEAOAAQAHAAAHABIAJADIAGACIACAEIABAEIAAAGIAAAGIgBAEIgCACIgCAAIgDgBIgFgBIgHgCIgJgBQgHAAgGACQgFACgDAFQgDAFgBAIQgCAIAAALIAAAUIAnAAIADAAIACADIACAEIAAAGQAAAHgCADQgCADgDAAIgnAAIAACZIAAADIgDACIgEABIgIAAg");
	this.shape_6.setTransform(676.15,42.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgnBaQgQgGgLgNQgLgMgEgRQgGgSAAgWQAAgVAGgRQAFgTALgNQALgNASgHQAQgIAWAAQAWAAAPAHQAQAGALAMQALANAGARQAFASAAAXQAAAUgGASQgFASgMANQgLANgQAHQgRAIgWAAQgWAAgQgHgAgXg/QgLAEgGAKQgHAJgDANQgEAMABAPQAAAOACANQADAMAGAKQAHAJAKAGQAKAFAPABQAOAAAKgGQALgEAGgKQAHgJADgNQAEgNAAgPQAAgNgEgNQgCgMgGgKQgGgKgKgFQgLgGgPAAQgOABgKAFg");
	this.shape_7.setTransform(659,46.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AABBzQgIgEgGgHQgHgHgCgLQgEgMAAgPIAAhmIgYAAQgDAAgCgDQgCgDABgHIAAgGIABgEIACgDIADAAIAYAAIAAgqIABgDIADgCIAEgBIAIgBIAJABIADABIADACIABADIAAAqIAtAAIACAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIACAEIABAGQgBAHgCADQgBADgDAAIgtAAIAABhQgBASAGAKQAFAJAPAAIAHgBIAGgCIAGgBIADgBIACAAIABACIABAEIABAFIgCAJIgCAFIgEADIgHADIgJABIgJABQgOAAgKgEg");
	this.shape_8.setTransform(632.4,44.175);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AA7BfIgIAAIgEgBIgDgCIgBgDIAAhmQAAgPgCgJQgCgJgFgHQgEgGgHgEQgIgDgJAAQgLAAgMAIQgMAJgOARIAAB5IAAADIgDACIgFABIgIAAIgIAAIgFgBIgCgCIgBgDIAAiuIABgDQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIAFgBIAHAAIAHAAIAEABIADACIAAADIAAAXQAPgRAPgHQAPgIAOAAQARAAAMAGQAMAGAIAKQAHAKADANQAEANAAATIAABqIgBADIgDACIgFABIgIAAg");
	this.shape_9.setTransform(615.925,46.275);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAACCIgHAAIgFgCIgCgBIgBgDIAAivIABgCIACgCIAFgBIAHAAIAIAAIAFABIACACIABACIAACvIgBADIgCABIgFACIgIAAgAgOhfQgFgDAAgLQAAgMAFgEQADgEALAAQAMAAADAEQAFAEAAALQAAALgFAEQgEAFgLAAQgKAAgEgFg");
	this.shape_10.setTransform(600.75,42.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgnBaQgQgGgLgNQgLgMgEgRQgGgSAAgWQAAgVAGgRQAFgTALgNQALgNASgHQAQgIAWAAQAVAAAQAHQAQAGALAMQALANAGARQAFASAAAXQAAAUgGASQgFASgLANQgMANgQAHQgRAIgWAAQgWAAgQgHgAgXg/QgLAEgGAKQgHAJgDANQgEAMABAPQAAAOACANQADAMAGAKQAHAJAKAGQAKAFAPABQAOAAAKgGQALgEAGgKQAHgJADgNQAEgNAAgPQAAgNgEgNQgCgMgGgKQgGgKgKgFQgLgGgPAAQgOABgKAFg");
	this.shape_11.setTransform(585.65,46.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AhICCIgFgBIgCgCIgBgDIAAj0IABgDIACgCIAFgBIAGAAIAHAAIAEABIADACIAAADIAAAXIAQgOQAHgGAIgEQAHgEAIgCQAHgCAJAAQATAAAOAHQANAIAJANQAIAMAEASQAEARAAATQAAAXgFARQgFATgKAMQgJANgPAHQgOAHgSAAQgHAAgHgCIgNgEQgGgEgGgFIgOgMIAABYIAAADIgDACIgFABIgIAAIgIAAgAgIhkQgGACgGAEQgGAEgHAHQgHAGgIAKIAABFQAOAQAMAJQAMAIAMAAQAMAAAJgGQAJgFAFgKQAFgKADgLQACgMAAgNQAAgNgCgNQgCgMgFgKQgFgKgIgGQgJgFgMAAQgGAAgGABg");
	this.shape_12.setTransform(565.225,49.775);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgoB/QgPgEgJgGQgKgHgEgIQgEgJAAgKQAAgHABgGQACgGADgFQADgGAFgFIALgKQgKgEgEgIQgFgHAAgJQAAgLAFgJQAFgKAHgHQgGgHgDgJQgEgJAAgNQAAgPAFgMQAFgMAJgIQAJgJANgEQAMgEAPAAIAOABQAHAAAGACIA1AAQAEAAABADQACADAAAHQAAAHgCADQgCADgDAAIgZAAQAHAHADAJQACAIAAAJQAAAPgEAMQgFAMgJAIQgJAIgNAEQgMAFgPAAQgKAAgKgDQgKgDgFgEQgEADgCAFQgCAEAAAFQAAAHAGAEQAHAFAKAAIAtACQANABALADQALADAIAGQAIAGAFAJQAEAIAAAMQAAAMgFALQgFALgKAIQgLAIgQAFQgQAFgVAAQgWAAgPgDgAgoA3IgHAJIgDAIIgBAIQAAAMANAHQANAGAXAAQAOAAAKgCQAJgDAHgFQAGgFACgGQADgGAAgGQAAgMgJgGQgKgGgQAAIgsgCIgKAJgAgUhmQgIAEgEAFQgFAFgCAIQgCAHAAAIQAAARAKAKQAKAKARAAQAJAAAHgDQAHgDAFgFQAEgGACgHQADgHAAgIQAAgSgKgKQgKgKgRAAQgKAAgGADg");
	this.shape_13.setTransform(535.625,49.825);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AA7BfIgIAAIgEgBIgDgCIgBgDIAAhmQAAgPgCgJQgCgJgFgHQgEgGgHgEQgIgDgJAAQgLAAgMAIQgMAJgOARIAAB5IAAADIgDACIgFABIgIAAIgIAAIgFgBIgCgCIgBgDIAAiuIABgDQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIAFgBIAHAAIAHAAIAEABIADACIAAADIAAAXQAPgRAPgHQAPgIAOAAQARAAAMAGQAMAGAIAKQAHAKADANQAEANAAATIAABqIgBADIgDACIgFABIgIAAg");
	this.shape_14.setTransform(515.875,46.275);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AAACCIgHAAIgFgCIgDgBIAAgDIAAivIAAgCIADgCIAFgBIAHAAIAIAAIAFABIADACIAAACIAACvIAAADIgDABIgFACIgIAAgAgPhfQgEgDAAgLQAAgMAEgEQAEgEALAAQALAAAFAEQAEAEAAALQAAALgEAEQgFAFgLAAQgLAAgEgFg");
	this.shape_15.setTransform(500.7,42.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AABBzQgIgEgHgHQgGgHgDgLQgDgMAAgPIAAhmIgYAAQgDAAgCgDQgBgDAAgHIAAgGIABgEIACgDIADAAIAYAAIAAgqIABgDIADgCIAFgBIAIgBIAIABIADABIADACIABADIAAAqIAtAAIADAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIACAEIAAAGQAAAHgCADQgBADgDAAIgtAAIAABhQgBASAGAKQAFAJAOAAIAIgBIAHgCIAEgBIAEgBIACAAIABACIABAEIAAAFIgBAJIgCAFIgFADIgGADIgJABIgJABQgOAAgKgEg");
	this.shape_16.setTransform(489.1,44.175);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAACIIgHAAIgFgBIgDgBIAAgEIAAkEIAAgCIADgCIAFgBIAHAAIAIAAIAFABIACACIABACIAAEEIgBAEIgCABIgFABIgIAAg");
	this.shape_17.setTransform(478.1,42.15);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgeBaQgQgFgMgNQgLgLgFgSQgGgSAAgYQAAgWAGgRQAGgTALgNQALgMAQgHQAPgGATgBQAUAAAPAHQAPAHAIALQAKALAEAPQAFAQAAARIAAAFQAAAHgEADQgEAEgFAAIhzAAQAAAOAEAMQACAMAIAIQAGAJALAEQALAEAPABQAMAAAKgCIARgFIAMgEIAHgDIACABIADACIAAAEIABAGIAAAEIgBAEIgBACIgCACIgGAEQgGACgIACIgTAFQgLABgNABQgVAAgQgHgAgShCQgJAEgGAIQgHAHgCALQgEAKgBAKIBgAAQAAgagMgOQgMgPgXAAQgLABgJAEg");
	this.shape_18.setTransform(463.5,46.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AByBfIgIAAIgFgBIgCgCIgBgDIAAhpQAAgMgCgJQgCgJgEgHQgFgGgGgEQgHgDgJAAQgLAAgLAIQgLAJgOARIAAB5IgBADIgCACIgFABIgIAAIgHAAIgFgBIgCgCIgBgDIAAhpQAAgMgCgJQgCgJgFgHQgEgGgGgEQgHgDgJAAQgLAAgMAIQgLAJgNARIAAB5IgBADIgCACIgFABIgIAAIgIAAIgFgBIgDgCIAAgDIAAiuIAAgDQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAEgBIAHAAIAIAAIAEABIACACIABADIAAAXQAPgRAOgHQAOgIAOAAQALAAAIACQAJADAHAFQAGAEAEAHQAFAGADAIQAJgKAIgHQAHgGAIgEQAHgEAHgCQAHgCAHAAQARAAAMAGQALAGAHAKQAHAKADANQADANAAAPIAABuIAAADIgDACIgFABIgIAAg");
	this.shape_19.setTransform(437.675,46.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgiBfIgIAAIgFgBIgDgCIAAgDIAAiuIAAgDQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAEgBIAHAAIAIAAIAEABIACACIABADIAAAZQAHgKAGgHQAHgHAEgDQAGgEAGgCIALgBIAGAAIAGABIAHACIAEACIABACIABACIAAAEIAAAHIAAAHIgBAFIgBADIgDAAIgDAAIgFgCIgHgCIgHgBQgFAAgFACQgFACgFAFIgKAMIgMASIAAByIgBADIgCACIgFABIgIAAg");
	this.shape_20.setTransform(406.775,46.275);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgeBaQgQgFgMgNQgLgLgFgSQgGgSAAgYQAAgWAGgRQAGgTALgNQALgMAPgHQAQgGASgBQAVAAAPAHQAOAHAKALQAJALAEAPQAFAQAAARIAAAFQAAAHgEADQgDAEgGAAIhyAAQAAAOADAMQACAMAHAIQAHAJALAEQALAEAPABQANAAAJgCIARgFIAMgEIAHgDIADABIACACIAAAEIABAGIAAAEIgBAEIgBACIgCACIgGAEQgGACgIACIgUAFQgLABgMABQgVAAgQgHgAgShCQgJAEgHAIQgFAHgEALQgDAKAAAKIBeAAQABgagMgOQgMgPgXAAQgLABgJAEg");
	this.shape_21.setTransform(388.65,46.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AABBzQgJgEgGgHQgGgHgDgLQgDgMAAgPIAAhmIgYAAQgDAAgCgDQgBgDAAgHIAAgGIABgEIACgDIADAAIAYAAIAAgqIABgDIADgCIAFgBIAIgBIAIABIADABIADACIABADIAAAqIAtAAIACAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIACAEIAAAGQAAAHgCADQgBADgDAAIgtAAIAABhQgBASAGAKQAFAJAOAAIAIgBIAGgCIAGgBIADgBIACAAIABACIABAEIAAAFIgBAJIgCAFIgEADIgHADIgJABIgJABQgOAAgKgEg");
	this.shape_22.setTransform(372.2,44.175);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AAACIIgHAAIgFgBIgDgBIAAgEIAAkEIAAgCIADgCIAFgBIAHAAIAIAAIAFABIADACIAAACIAAEEIAAAEIgDABIgFABIgIAAg");
	this.shape_23.setTransform(361.2,42.15);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgjBdQgMgDgHgIQgIgGgFgKQgEgKAAgNQAAgOAGgMQAGgKALgHQALgHARgDQAQgEAUAAIAYAAIAAgOQAAgKgCgIQgCgHgFgGQgFgFgHgCQgIgEgLAAQgLAAgJAEQgKADgHADIgMAGQgFADgCAAIgDgBIgCgCIgBgEIgBgFIABgIQABgDACgDIAJgFIAPgHIATgEQAKgDAJAAQATAAANAFQANAEAIAIQAJAJADAMQAEANAAAQIAAB2QAAAAAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgEABIgIABIgIgBIgEgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIAAgSQgLAMgOAHQgPAGgOABQgOgBgLgDgAgKAKQgJACgHAFQgGAFgDAFQgDAHAAAIQAAAOAJAHQAIAJAQgBQALAAALgGQALgHAMgNIAAglIgcAAQgMAAgKACg");
	this.shape_24.setTransform(346.475,46.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgYBgIgOgFIgMgEIgHgFQgCgCgBgDIgBgJIAAgHIABgEIACgCIADgBQABAAAFADIAKAFIAOAHQAJACALAAQAHAAAGgCQAIgCAEgDQAFgEADgFQADgFAAgHQgBgHgEgGQgDgFgHgEQgFgEgJgCIgOgHIgRgIQgIgDgGgFQgHgHgDgIQgEgJAAgMQAAgKAEgJQAEgJAIgIQAIgHANgEQALgFAPAAIAOABIANAEIAKADIAGAEIADADIAAACIABAEIAAAFIAAAGIgBAEIgBADIgDAAIgFgCQgDgCgGgCIgMgGQgHgCgJAAQgHAAgHACQgGACgEAEQgEADgCAFQgCAFAAAFQAAAHAEAGQAEAFAGAEIANAHIAQAHIARAHQAIADAHAGQAFAGAFAHQADAJAAAMQAAANgEAKQgGALgJAHQgJAHgNAEQgMADgPABIgSgBg");
	this.shape_25.setTransform(320.55,46.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgeBaQgQgFgLgNQgMgLgFgSQgGgSAAgYQAAgWAGgRQAGgTALgNQALgMAQgHQAPgGATgBQAUAAAPAHQAPAHAIALQAKALAFAPQAEAQAAARIAAAFQAAAHgEADQgEAEgEAAIh0AAQAAAOADAMQAEAMAHAIQAGAJALAEQALAEAPABQAMAAALgCIARgFIALgEIAHgDIACABIACACIABAEIABAGIAAAEIgBAEIgBACIgCACIgHAEQgEACgJACIgTAFQgLABgNABQgUAAgRgHgAgShCQgJAEgGAIQgHAHgCALQgEAKgBAKIBgAAQAAgagMgOQgMgPgXAAQgLABgJAEg");
	this.shape_26.setTransform(302.75,46.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AhICCIgFgBIgCgCIgBgDIAAj0IABgDIACgCIAFgBIAGAAIAHAAIAEABIADACIAAADIAAAXIAQgOQAHgGAIgEQAHgEAIgCQAHgCAJAAQATAAAOAHQANAIAJANQAIAMAEASQAEARAAATQAAAXgFARQgFATgKAMQgJANgPAHQgOAHgSAAQgHAAgHgCIgNgEQgGgEgGgFIgOgMIAABYIAAADIgDACIgFABIgIAAIgIAAgAgIhkQgGACgGAEQgGAEgHAHQgHAGgIAKIAABFQAOAQAMAJQAMAIAMAAQAMAAAJgGQAJgFAFgKQAFgKADgLQACgMAAgNQAAgNgCgNQgCgMgFgKQgFgKgIgGQgJgFgMAAQgGAAgGABg");
	this.shape_27.setTransform(282.975,49.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgmBaQgRgGgKgNQgMgMgEgRQgGgSAAgWQAAgVAGgRQAFgTAMgNQAKgNASgHQAQgIAVAAQAXAAAPAHQARAGAKAMQALANAFARQAGASAAAXQAAAUgGASQgGASgLANQgLANgRAHQgQAIgWAAQgVAAgQgHgAgXg/QgLAEgGAKQgHAJgDANQgEAMABAPQgBAOADANQADAMAGAKQAGAJALAGQAKAFAPABQAOAAALgGQAJgEAIgKQAGgJAEgNQACgNABgPQgBgNgCgNQgDgMgGgKQgGgKgKgFQgLgGgQAAQgNABgKAFg");
	this.shape_28.setTransform(261.4,46.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AACBzQgKgEgFgHQgHgHgCgLQgDgMgBgPIAAhmIgYAAQgDAAgCgDQgBgDgBgHIABgGIABgEIACgDIADAAIAYAAIAAgqIACgDIACgCIAEgBIAIgBIAIABIAFABIACACIABADIAAAqIAtAAIACAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAABABIABAEIABAGQAAAHgCADQgCADgDAAIgtAAIAABhQAAASAFAKQAGAJAOAAIAIgBIAFgCIAGgBIADgBIACAAIABACIABAEIABAFIgBAJIgDAFIgEADIgIADIgIABIgJABQgOAAgJgEg");
	this.shape_29.setTransform(244.25,44.175);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgnBaQgQgGgLgNQgLgMgFgRQgFgSAAgWQAAgVAFgRQAGgTALgNQALgNARgHQASgIAVAAQAVAAARAHQAPAGALAMQALANAGARQAFASAAAXQAAAUgGASQgFASgLANQgMANgQAHQgRAIgWAAQgWAAgQgHgAgXg/QgKAEgHAKQgHAJgDANQgDAMAAAPQAAAOACANQADAMAGAKQAHAJAKAGQAKAFAPABQAOAAAKgGQALgEAGgKQAHgJADgNQAEgNAAgPQAAgNgEgNQgCgMgGgKQgGgKgKgFQgLgGgPAAQgOABgKAFg");
	this.shape_30.setTransform(227.35,46.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgYBgIgOgFIgMgEIgHgFQgCgCgBgDIgBgJIAAgHIABgEIACgCIADgBQABAAAFADIAKAFIAOAHQAJACALAAQAHAAAGgCQAIgCAEgDQAFgEADgFQADgFAAgHQgBgHgEgGQgDgFgHgEQgFgEgJgCIgOgHIgRgIQgIgDgGgFQgHgHgDgIQgEgJAAgMQAAgKAEgJQAEgJAIgIQAIgHANgEQALgFAPAAIAOABIANAEIAKADIAGAEIADADIAAACIABAEIAAAFIAAAGIgBAEIgBADIgDAAIgFgCQgDgCgGgCIgMgGQgHgCgJAAQgHAAgHACQgGACgEAEQgEADgCAFQgCAFAAAFQAAAHAEAGQAEAFAGAEIANAHIAQAHIARAHQAIADAHAGQAFAGAFAHQADAJAAAMQAAANgEAKQgGALgJAHQgJAHgNAEQgMADgPABIgSgBg");
	this.shape_31.setTransform(208.95,46.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAACCIgHAAIgFgCIgCgBIgBgDIAAivIABgCIACgCIAFgBIAHAAIAIAAIAFABIACACIABACIAACvIgBADIgCABIgFACIgIAAgAgOhfQgFgDAAgLQAAgMAFgEQADgEALAAQAMAAADAEQAFAEAAALQAAALgFAEQgEAFgLAAQgKAAgEgFg");
	this.shape_32.setTransform(196.55,42.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AA7BfIgIAAIgEgBIgDgCIgBgDIAAhmQAAgPgCgJQgCgJgFgHQgEgGgHgEQgIgDgJAAQgLAAgMAIQgMAJgOARIAAB5IAAADIgDACIgFABIgIAAIgIAAIgFgBIgCgCIgBgDIAAiuIABgDQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIAFgBIAHAAIAHAAIAEABIADACIAAADIAAAXQAPgRAPgHQAPgIAOAAQARAAAMAGQAMAGAIAKQAHAKADANQAEANAAATIAABqIgBADIgDACIgFABIgIAAg");
	this.shape_33.setTransform(172.525,46.275);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgeBaQgQgFgMgNQgKgLgGgSQgGgSAAgYQAAgWAGgRQAGgTALgNQALgMAPgHQAQgGASgBQAVAAAPAHQAOAHAKALQAJALAEAPQAFAQAAARIAAAFQAAAHgEADQgDAEgGAAIhyAAQAAAOADAMQACAMAIAIQAGAJALAEQALAEAPABQANAAAJgCIARgFIAMgEIAHgDIADABIACACIAAAEIABAGIAAAEIgBAEIgBACIgCACIgGAEQgFACgJACIgUAFQgLABgMABQgUAAgRgHgAgShCQgJAEgGAIQgGAHgEALQgDAKAAAKIBeAAQABgagMgOQgMgPgXAAQgLABgJAEg");
	this.shape_34.setTransform(151.95,46.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgoB/QgPgEgJgGQgKgHgEgIQgEgJAAgKQAAgHABgGQACgGADgFQADgGAFgFIALgKQgKgEgEgIQgFgHAAgJQAAgLAFgJQAFgKAHgHQgGgHgDgJQgEgJAAgNQAAgPAFgMQAFgMAJgIQAJgJANgEQAMgEAPAAIAOABQAHAAAGACIA1AAQAEAAABADQACADAAAHQAAAHgCADQgCADgDAAIgZAAQAHAHADAJQACAIAAAJQAAAPgEAMQgFAMgJAIQgJAIgNAEQgMAFgPAAQgKAAgKgDQgKgDgFgEQgEADgCAFQgCAEAAAFQAAAHAGAEQAHAFAKAAIAtACQANABALADQALADAIAGQAIAGAFAJQAEAIAAAMQAAAMgFALQgFALgKAIQgLAIgQAFQgQAFgVAAQgWAAgPgDgAgoA3IgHAJIgDAIIgBAIQAAAMANAHQANAGAXAAQAOAAAKgCQAJgDAHgFQAGgFACgGQADgGAAgGQAAgMgJgGQgKgGgQAAIgsgCIgKAJgAgUhmQgIAEgEAFQgFAFgCAIQgCAHAAAIQAAARAKAKQAKAKARAAQAJAAAHgDQAHgDAFgFQAEgGACgHQADgHAAgIQAAgSgKgKQgKgKgRAAQgKAAgGADg");
	this.shape_35.setTransform(132.925,49.825);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgnBaQgQgGgLgNQgLgMgFgRQgFgSAAgWQAAgVAFgRQAGgTALgNQALgNARgHQASgIAVAAQAVAAARAHQAPAGALAMQALANAGARQAFASAAAXQAAAUgGASQgFASgLANQgMANgQAHQgRAIgWAAQgWAAgQgHgAgXg/QgKAEgHAKQgHAJgDANQgDAMAAAPQAAAOACANQADAMAGAKQAHAJAKAGQAKAFAPABQAOAAAKgGQALgEAGgKQAHgJADgNQAEgNAAgPQAAgNgEgNQgCgMgGgKQgGgKgKgFQgLgGgPAAQgOABgKAFg");
	this.shape_36.setTransform(113.05,46.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgiBfIgIAAIgFgBIgDgCIAAgDIAAiuIAAgDQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAEgBIAHAAIAIAAIAEABIACACIABADIAAAZQAHgKAGgHQAHgHAEgDQAGgEAGgCIALgBIAGAAIAGABIAHACIAEACIABACIABACIAAAEIAAAHIAAAHIgBAFIgBADIgDAAIgDAAIgFgCIgHgCIgHgBQgFAAgFACQgFACgFAFIgKAMIgMASIAAByIgBADIgCACIgFABIgIAAg");
	this.shape_37.setTransform(97.325,46.275);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgqCCQgNgIgJgMQgIgNgEgRQgEgRAAgUQAAgWAFgSQAFgSAJgNQAKgMAOgIQAOgGATgBQAOABANAGQANAHAMANIAAhmIABgCQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABgBIAFgBIAHgBIAIABIAFABIADADIABACIAAEDIgBADIgCACIgFABIgGAAIgHAAIgFgBIgCgCIgBgDIAAgXQgOAPgPAJQgPAHgRABQgTAAgOgIgAgWgVQgJAGgFAKQgGAIgCAMQgDANAAAMQAAANADANQACANAFAJQAFALAIAFQAIAGANAAQAGAAAGgBQAGgDAGgDQAGgEAHgHQAHgGAHgKIAAhHQgNgOgMgJQgMgJgMAAQgNAAgIAGg");
	this.shape_38.setTransform(78.225,42.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgfCAIgFgBIgCgDIABgFIAYg9IgDgDIgCgDIg/inIgCgHQAAAAAAgBQAAgBABAAQAAgBAAAAQAAAAABgBIAFgBIAJgBIAKAAIAFABIADADIACAEIAxCMIAAAAIAxiNQABgEACgBIAFgBIAJgBIAJABIAFABQABABAAAAQAAAAAAABQABAAAAABQAAABAAAAIgBAGIg/CuIgXBAQgBAEgFABQgEACgKAAIgIgBg");
	this.shape_39.setTransform(59.625,49.925);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("ABLB/IgIAAIgGgBIgCgCIgBgDIAAhvIhzAAIAABvIAAADIgDACIgFABIgIAAIgIAAIgFgBQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAIgBgDIAAjxIABgDIADgBIAFgCIAIAAIAIAAIAFACIADABIAAADIAABlIBzAAIAAhlIABgDIACgBIAGgCIAIAAIAIAAIAEACIADABIABADIAADxIgBADIgDACIgEABIgIAAg");
	this.shape_40.setTransform(38.15,43.05);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgzB6QgUgJgOgQQgOgQgGgYQgHgYAAgfQAAgdAHgZQAHgYAOgRQAPgRAWgKQAVgJAdAAQAbAAAVAIQAVAJANAQQAOAQAHAYQAHAYAAAeQAAAegIAZQgGAYgPARQgPASgVAJQgVAJgdAAQgcAAgVgIgAgjhcQgPAIgKAOQgJAOgDASQgFASAAAUQABAVADATQAEATAJAOQAJANAOAHQAPAIAWAAQAVAAAPgIQAPgJAJgNQAKgOAEgTQADgSAAgUQAAgVgDgTQgEgSgJgNQgJgOgPgIQgPgHgVAAQgWAAgOAIg");
	this.shape_41.setTransform(551.45,451.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgrBTIgEAAIgCgCIgBgDIAAgEIAAgFIAAgDIACgDIADgDIAggiIASgVIAKgQQAEgHACgHIAAgLQAAgGgBgFQgCgEgEgEQgDgEgGgCQgEgCgGAAQgJAAgGACIgLAFIgIAEIgEADIgCgBIgCgCIAAgDIgBgEIAAgEIABgCIABgCIACgCIAFgEIAJgEIANgEQAHgBAHAAQALAAAKADQAIADAGAGQAGAGADAIQADAHAAAJQAAAIgCAIQgBAIgEAJQgFAIgJALQgIALgOAPIgZAbIBHAAIABAAIACACIABADIAAAEIAAAEIgBADIgCACIgBAAg");
	this.shape_42.setTransform(531.65,459.275);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAAB/IgHAAIgFgCQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgCIAAjaIhHAAIgCgBIgDgDIgBgEIAAgHIAAgGIABgFIADgCIACgBICvAAIADABIACACIABAFIABAGIgBAHIgBAEIgCADIgDABIhHAAIAADaIgBACIgDACIgFACIgIAAg");
	this.shape_43.setTransform(515.3,451.275);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgzB6QgVgJgNgQQgOgQgHgYQgGgYAAgfQAAgdAHgZQAHgYAPgRQAOgRAWgKQAWgJAbAAQAdAAAUAIQAVAJAOAQQAOAQAGAYQAHAYAAAeQAAAegHAZQgIAYgOARQgPASgVAJQgWAJgbAAQgdAAgVgIgAgjhcQgPAIgKAOQgIAOgEASQgEASgBAUQAAAVAEATQAEATAIAOQAKANAOAHQAPAIAWAAQAVAAAPgIQAPgJAKgNQAIgOAEgTQAFgSAAgUQAAgVgFgTQgDgSgJgNQgJgOgPgIQgPgHgWAAQgVAAgOAIg");
	this.shape_44.setTransform(350.6,451.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgsBTIgCAAIgCgCIgCgDIgBgEIAAgFIABgDIACgDIADgDIAhgiIARgVIALgQQADgHABgHIABgLQAAgGgCgFQgBgEgDgEQgEgEgFgCQgGgCgGAAQgHAAgHACIgLAFIgIAEIgFADIgBgBIgBgCIgBgDIAAgEIAAgEIAAgCIABgCIACgCIAGgEIAJgEIAMgEQAHgBAIAAQALAAAIADQAJADAGAGQAGAGADAIQADAHAAAJQAAAIgBAIQgCAIgFAJQgEAIgIALQgJALgOAPIgZAbIBGAAIACAAIACACIABADIABAEIgBAEIgBADIgCACIgCAAg");
	this.shape_45.setTransform(330.8,459.275);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AhUB+QgEAAgEgDQgEgDAAgHIAAjhQAAgHAEgDQAEgDAEAAIA6AAQAfAAAXAIQAXAJAPAQQAPAPAIAXQAIAXAAAcQAAAggIAZQgJAYgQAQQgQAQgXAIQgYAIgfAAgAg/BiIAjAAQAYAAAQgGQAQgGAMgMQALgNAFgTQAGgTAAgYQAAgVgFgSQgFgRgLgNQgLgNgRgHQgPgIgaAAIgjAAg");
	this.shape_46.setTransform(312.675,451.225);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgzB6QgVgJgNgQQgOgQgHgYQgGgYAAgfQAAgdAHgZQAHgYAPgRQAOgRAWgKQAWgJAbAAQAdAAAUAIQAVAJANAQQAPAQAGAYQAHAYAAAeQAAAegHAZQgIAYgOARQgPASgVAJQgWAJgbAAQgdAAgVgIgAgjhcQgPAIgKAOQgIAOgEASQgFASAAAUQAAAVAEATQAEATAIAOQAKANAOAHQAPAIAWAAQAVAAAPgIQAPgJAKgNQAIgOAEgTQAEgSABgUQgBgVgEgTQgDgSgJgNQgJgOgPgIQgPgHgVAAQgVAAgPAIg");
	this.shape_47.setTransform(145.75,451.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgrBTIgDAAIgDgCIgBgDIgBgEIAAgFIABgDIACgDIADgDIAggiIASgVIALgQQADgHABgHIABgLQAAgGgCgFQgBgEgDgEQgEgEgFgCQgGgCgGAAQgHAAgHACIgLAFIgIAEIgEADIgCgBIgBgCIgBgDIAAgEIAAgEIAAgCIABgCIACgCIAGgEIAJgEIAMgEQAHgBAIAAQAKAAAKADQAIADAGAGQAGAGADAIQADAHAAAJQAAAIgBAIQgCAIgFAJQgEAIgIALQgJALgOAPIgZAbIBGAAIACAAIACACIABADIABAEIgBAEIgBADIgCACIgCAAg");
	this.shape_48.setTransform(125.95,459.275);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("ABLB/IgIAAIgGgBIgCgCIgBgDIAAhvIhyAAIAABvIgBADIgDACIgFABIgIAAIgIAAIgFgBQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAIgBgDIAAjxIABgDIADgBIAFgCIAIAAIAIAAIAFACIADABIABADIAABlIByAAIAAhlIABgDIACgBIAGgCIAIAAIAHAAIAGACIACABIABADIAADxIgBADIgCACIgGABIgHAAg");
	this.shape_49.setTransform(106.9,451.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgKAMQgDgDAAgJQAAgIADgDQADgDAHAAQAIAAADADQADADAAAIQAAAJgDADQgDADgIAAQgHAAgDgDg");
	this.shape_50.setTransform(1031.075,504.625);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgTA7QgLgEgHgIQgHgIgEgLQgEgMAAgQQAAgNAEgMQAEgMAHgIQAHgIALgEQAKgFALAAQAOAAAJAEQAJAFAHAHQAGAHADAKQACAKAAALIAAAEQAAAEgCACQgDACgDAAIhKAAQAAAKACAHQACAIAFAFQADAGAIADQAHADAKAAQAIAAAGgCIALgDIAIgDIAEgBIABABIACABIABACIAAAEIAAADIgBACIgBACIgBABIgDADIgJADIgNADIgPABQgOAAgKgEgAgLgrQgHADgDAFQgFAFgCAGQgCAHAAAHIA+AAQAAgRgIgJQgIgKgPAAQgHAAgFADg");
	this.shape_51.setTransform(1021.3,499.975);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgbA+IgDgBIgCgBIAAgCIAAhxIAAgCIACgCIACAAIAFgBIAFABIADAAIABACIABACIAAAQIAIgLIAHgGQAEgDAEgBIAHgBIAEAAIAEAAIAEACIADABIABACIAAABIAAACIAAAFIAAAFIAAADIgBACIgCAAIgCAAIgDgCIgFgBIgFgBIgGACIgGAEIgGAIIgIALIAABLIgBACIgCABIgDABIgFAAIgFAAg");
	this.shape_52.setTransform(1011.425,499.9);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AgbA6QgIgEgEgGQgFgHgCgJQgCgIAAgMIAAhFIAAgBIACgCIADAAIAFgBIAFABIADAAIACACIABABIAABCQAAAJABAGQACAHADAEQADAEAEACQAFADAGAAQAHAAAHgFQAIgHAJgKIAAhPIAAgBIACgCIADAAIAGgBIAFABIADAAIACACIAAABIAAByIAAABIgCABIgDABIgEAAIgFAAIgDgBIgCgBIAAgBIAAgQQgKALgJAFQgKAFgJAAQgLAAgIgEg");
	this.shape_53.setTransform(999.325,500.05);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AARBNQgJAAgHgCQgFgCgEgFQgFgFgBgHQgCgIAAgJIAAhDIgQAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQgBgCAAgEIAAgEIABgCIABgCIACgBIAQAAIAAgbIABgCIABgBIADAAIAFgBIAGABIACAAIABABIABACIAAAbIAdAAIACABIACACIAAACIABAEQgBAEgBACQAAABgBAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAIAAA/QAAAMAEAGQADAHAJAAIAFgBIAEgBIADgBIADgBIABAAIABABIAAADIABADIgBAGIgBADIgEADIgEABIgGABIgFAAg");
	this.shape_54.setTransform(987.95,498.5);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgXA8QgHgCgFgEQgFgFgDgGQgDgHAAgIQAAgKAEgHQAEgHAIgEQAHgEALgDQAKgCAMAAIAQAAIAAgJIgBgMQgBgFgEgDQgDgDgFgCQgEgCgIAAQgHAAgGACIgLAEIgIAEIgEACIgCgBIgBgBIgBgDIAAgDIABgFQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBIAFgEIAKgEIAMgDIAMgBQAMAAAJADQAIADAGAFQAFAFACAIQADAIAAALIAABMIgBACIgDACIgFAAIgFAAIgDgCIgBgCIAAgLQgIAIgJAEQgJAFgJAAQgJAAgIgDgAgGAHQgGABgEADQgEADgDAEQgCAEAAAFQAAAJAHAFQAFAFAKAAQAIAAAGgEQAIgEAHgJIAAgYIgSAAQgIAAgGACg");
	this.shape_55.setTransform(977.45,499.975);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgbA+IgDgBIgCgBIAAgCIAAhxIAAgCIACgCIACAAIAFgBIAFABIADAAIABACIABACIAAAQIAIgLIAHgGQAEgDAEgBIAHgBIAEAAIAEAAIAEACIADABIABACIAAABIAAACIAAAFIAAAFIAAADIgBACIgCAAIgCAAIgDgCIgFgBIgFgBIgGACIgGAEIgGAIIgIALIAABLIgBACIgCABIgDABIgFAAIgFAAg");
	this.shape_56.setTransform(968.375,499.9);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgTA7QgLgEgHgIQgHgIgEgLQgDgMAAgQQAAgNADgMQAEgMAHgIQAHgIAKgEQALgFALAAQANAAAKAEQAJAFAHAHQAFAHAEAKQACAKAAALIAAAEQABAEgDACQgCACgEAAIhKAAQAAAKACAHQACAIAFAFQADAGAIADQAHADAJAAQAJAAAGgCIALgDIAIgDIAEgBIABABIACABIABACIAAAEIAAADIgBACIAAACIgCABIgEADIgJADIgMADIgPABQgOAAgKgEgAgMgrQgFADgEAFQgEAFgDAGQgCAHAAAHIA+AAQgBgRgHgJQgIgKgPAAQgHAAgGADg");
	this.shape_57.setTransform(956.6,499.975);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AgpBUIgFAAIgEgBIgBgBIgBgBIAAifIABgBIABgCIADAAIAEgBIAFABIADAAIABACIABABIAAAQIAKgKQAEgEAFgDIALgDQADgBAHAAQAMgBAIAFQAKAFAFAJQAGAIACALQACALABAMQAAAPgDALQgEAMgGAJQgHAIgJAEQgJAFgMAAIgJgBIgIgEIgIgFIgIgHIAAA5IgBABIgCABIgDABIgFAAgAgFhAIgHADIgJAIIgJAJIAAAtQAIAKAIAHQAHAFAIAAQAIAAAGgEQAGgEADgGQADgGACgIQACgHAAgIQAAgJgCgIQgBgIgDgHQgDgGgGgEQgFgDgJAAIgHABg");
	this.shape_58.setTransform(943.7,502.15);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("ABFA+IgDgBIgCgBIAAgCIAAhEQAAgIgCgGQgBgGgDgEQgDgFgEgCQgEgCgGAAQgHAAgHAGQgIAFgJALIAABPIAAACIgCABIgDABIgFAAIgEAAIgDgBIgCgBIgBgCIAAhEIgBgOQgBgGgDgEQgDgFgEgCQgEgCgGAAQgIAAgHAGQgHAFgJALIAABPIAAACIgCABIgDABIgFAAIgFAAIgEgBIgBgBIgBgCIAAhxIABgCIABgCIADAAIAFgBIAEABIADAAIACACIAAACIAAAOQAKgKAJgFQAJgFAJAAQAHAAAGABQAGACAEADQAEADACAFIAFAJIALgLQAFgEAFgDIAJgEIAJgBQALAAAIAEQAHAEAFAGQAFAHACAIQACAJAAAJIAABIIgBACIgCABIgDABIgFAAIgFAAg");
	this.shape_59.setTransform(926.175,499.9);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AgTA7QgLgEgHgIQgHgIgEgLQgEgMAAgQQAAgNAEgMQAEgMAHgIQAHgIALgEQAKgFALAAQAOAAAJAEQAJAFAHAHQAGAHADAKQACAKAAALIAAAEQABAEgDACQgDACgDAAIhKAAQAAAKACAHQACAIAFAFQADAGAIADQAHADAJAAQAJAAAGgCIALgDIAIgDIAEgBIABABIACABIABACIAAAEIAAADIgBACIgBACIgBABIgDADIgJADIgNADIgPABQgOAAgKgEgAgLgrQgHADgDAFQgFAFgCAGQgCAHAAAHIA+AAQAAgRgIgJQgIgKgPAAQgHAAgFADg");
	this.shape_60.setTransform(909.25,499.975);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AAQBNQgIAAgHgCQgFgCgFgFQgEgFgBgHQgCgIAAgJIAAhDIgQAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQgBgCgBgEIABgEIABgCIABgCIACgBIAQAAIAAgbIABgCIABgBIADAAIAGgBIAEABIADAAIACABIAAACIAAAbIAdAAIACABIABACIABACIABAEQAAAEgCACQAAABgBAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAIAAA/QAAAMADAGQAEAHAJAAIAFgBIAEgBIADgBIACgBIABAAIABABIABADIABADIgBAGIgCADIgDADIgFABIgFABIgGAAg");
	this.shape_61.setTransform(898.55,498.5);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgTA7QgLgEgHgIQgIgIgDgLQgEgMABgQQgBgNAEgMQAEgMAHgIQAIgIAJgEQAKgFAMAAQANAAAKAEQAKAFAFAHQAHAHACAKQADAKABALIAAAEQAAAEgDACQgCACgDAAIhLAAQAAAKACAHQACAIAEAFQAFAGAHADQAHADAJAAQAIAAAHgCIALgDIAHgDIAFgBIACABIABABIAAACIAAAEIAAADIAAACIAAACIgBABIgFADIgJADIgMADIgQABQgMAAgLgEgAgMgrQgFADgFAFQgDAFgCAGQgDAHAAAHIA9AAQAAgRgHgJQgIgKgPAAQgGAAgHADg");
	this.shape_62.setTransform(963.65,466.225);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgZBSQgKgCgGgEQgGgEgDgGQgDgGAAgGIABgIIADgIIAFgGIAHgHQgGgDgDgFQgDgFAAgFQAAgHADgGIAIgLQgEgFgCgGQgCgGAAgIQAAgKADgIQADgHAGgGQAGgFAIgDQAIgDAKAAIAJABIAIACIAjAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAABIABAGIgBAGQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgRAAQAFAFACAGIABALQAAAKgDAIQgDAHgGAFQgGAGgIACQgIADgJAAQgHAAgGgCQgGgBgEgDIgEAFQgBADAAADQAAAEAEADQAEADAHAAIAdACQAIAAAIACQAHACAFAEQAFAEADAFQADAGAAAHQAAAIgDAHQgEAIgGAFQgHAFgLAEQgKADgOAAQgOAAgJgDgAgaAkIgEAGIgCAFIAAAFQAAAIAIAEQAIAFAPAAQAJAAAGgCQAHgCAEgDQADgDACgEIACgIQAAgIgGgEQgGgEgKAAIgdgBIgHAGgAgNhCQgEACgDAEQgDAEgCAEQgBAFAAAFQAAALAGAHQAHAGALAAQAFAAAFgCQAFgCADgDIAEgIQABgFAAgFQAAgMgGgGQgGgHgLAAQgGAAgFACg");
	this.shape_63.setTransform(951.225,468.425);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AAhA+IgDgBIgBgBIgBgCIAAhCQAAgKgBgGQgCgGgDgEQgDgFgEgCQgFgCgGAAQgHAAgIAGQgIAFgIALIAABPIgBACIgCABIgDABIgFAAIgFAAIgDgBIgCgBIAAgCIAAhxIAAgCIACgCIACAAIAFgBIAFABIADAAIABACIABACIAAAOQAJgKAKgFQAJgFAJAAQAMAAAHAEQAIAEAFAGQAFAHACAIQACAJAAAMIAABFIAAACIgCABIgDABIgFAAIgGAAg");
	this.shape_64.setTransform(938.375,466.15);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgWA8QgIgCgFgEQgFgFgDgGQgDgHAAgIQAAgKAEgHQAEgHAIgEQAHgEALgDQAKgCAMAAIAQAAIAAgJIgBgMQgBgFgEgDQgDgDgFgCQgFgCgHAAQgGAAgHACIgLAEIgHAEIgFACIgCgBIgBgBIgBgDIAAgDIABgFQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBIAGgEIAJgEIAMgDIAMgBQAMAAAJADQAIADAGAFQAFAFACAIQADAIAAALIAABMIgBACIgDACIgFAAIgFAAIgDgCIgBgCIAAgLQgIAIgIAEQgKAFgJAAQgJAAgHgDgAgGAHQgGABgEADQgFADgBAEQgDAEAAAFQABAJAGAFQAFAFAKAAQAIAAAGgEQAHgEAIgJIAAgYIgSAAQgIAAgGACg");
	this.shape_65.setTransform(924.9,466.225);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AAhBZIgDgBIgBgBIgBgCIAAhDQAAgKgBgGQgCgFgDgEQgDgFgEgCQgFgCgGAAQgHAAgIAGQgIAFgIAKIAABQIgBACIgCABIgDABIgFAAIgFAAIgDgBIgCgBIAAgCIAAipIAAgCIACgBIADgBIAFAAIAFAAIADABIACABIABACIAABEQAJgJAJgEQAJgFAIAAQAMAAAHAEQAIAEAFAGQAFAHACAIQACAIAAANIAABFIAAACIgCABIgDABIgFAAIgGAAg");
	this.shape_66.setTransform(912.275,463.45);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AgPA7QgKgEgGgIQgGgIgEgLQgDgMAAgPQAAgQAEgMQAEgMAIgIQAGgHALgEQAJgEAKAAIALABIAJADIAIAEIAFADIACADIABACIABADIAAADIgBAHQgBABAAAAQAAABgBAAQAAAAgBAAQAAAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBIgGgEIgJgFQgGgCgHAAQgOAAgIAMQgIALAAAVQAAALACAJQACAIAEAFQAEAGAGADQAFADAHAAQAHAAAGgDIAJgFIAHgFIAFgCIABABIACABIAAADIAAAFIAAADIAAADIgBACIgCACIgGAEIgIAFIgLADIgLABQgMAAgJgEg");
	this.shape_67.setTransform(900.05,466.225);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgYA6QgLgEgHgIQgHgIgEgLQgDgMAAgOQAAgNADgMQAEgLAIgJQAHgIALgFQAKgFAOAAQAOAAALAEQAKAEAHAIQAHAIAEAMQADALAAAPQAAANgEALQgDAMgIAJQgHAIgLAFQgLAFgNAAQgPAAgJgFgAgOgpQgHADgFAGQgEAGgCAJQgDAIAAAJQAAAJADAIQABAIAEAHQAEAGAHADQAHAEAJAAQAJAAAHgDQAHgEAEgGQAEgGACgIQACgIAAgKQAAgIgCgIQgBgJgEgGQgEgGgHgEQgGgDgLAAQgIAAgGADg");
	this.shape_68.setTransform(998,432.475);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AAQBNQgIAAgHgCQgFgCgFgFQgEgFgBgHQgCgIAAgJIAAhDIgQAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQgCgCAAgEIABgEIABgCIABgCIACgBIAQAAIAAgbIABgCIABgBIADAAIAGgBIAEABIADAAIACABIAAACIAAAbIAdAAIACABIACACIAAACIABAEQAAAEgCACQAAABgBAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAIAAA/QAAAMADAGQAEAHAJgBIAFAAIAEgBIADgBIACgBIABAAIACABIAAACIABAEIgBAGIgCADIgDADIgEABIgGABIgGAAg");
	this.shape_69.setTransform(986.85,431);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AgpBUIgFAAIgDgBIgCgBIgBgBIAAifIABgBIACgCIACAAIAEgBIAFABIADAAIABACIABABIAAAQIAKgKQAEgEAGgDIAKgDQADgBAHAAQAMgBAIAFQAKAFAFAJQAGAIACALQACALAAAMQABAPgDALQgEAMgGAJQgGAIgKAEQgJAFgMAAIgJgBIgHgEIgJgFIgIgHIAAA5IgBABIgCABIgDABIgFAAgAgEhAIgIADIgJAIIgJAJIAAAtQAIAKAIAHQAIAFAHAAQAIAAAGgEQAGgEADgGQAEgGABgIQACgHAAgIQAAgJgCgIQgBgIgDgHQgDgGgGgEQgFgDgJAAIgGABg");
	this.shape_70.setTransform(970.35,434.65);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AgbA6QgIgEgEgGQgFgHgCgJQgCgIAAgMIAAhFIAAgBIACgCIADAAIAFgBIAFABIADAAIACACIABABIAABCQAAAJABAGQACAHADAEQADAEAEACQAFADAGAAQAHAAAHgFQAIgHAJgKIAAhPIAAgBIACgCIADAAIAGgBIAFABIADAAIACACIAAABIAAByIAAABIgCABIgDABIgEAAIgFAAIgDgBIgCgBIAAgBIAAgQQgKALgJAFQgKAFgJAAQgLAAgIgEg");
	this.shape_71.setTransform(956.325,432.55);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AgZBSQgKgCgGgEQgGgEgDgGQgDgGAAgGIABgIIADgIIAFgGIAHgHQgGgDgDgFQgDgFAAgFQAAgHADgGIAIgLQgEgFgCgGQgCgGAAgIQAAgKADgIQADgHAGgGQAGgFAIgDQAIgDAKAAIAJABIAIACIAjAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAABIABAGIgBAGQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgRAAQAFAFACAGIABALQAAAKgDAIQgDAHgGAFQgGAGgIACQgIADgJAAQgHAAgGgCQgGgBgEgDIgEAFQgBADAAADQAAAEAEADQAEADAHAAIAdACQAIAAAIACQAHACAFAEQAFAEADAFQADAGAAAHQAAAIgDAHQgEAIgGAFQgHAFgLAEQgKADgOAAQgOAAgJgDgAgaAkIgEAGIgCAFIAAAFQAAAIAIAEQAIAFAPAAQAJAAAGgCQAHgCAEgDQADgDACgEIACgIQAAgIgGgEQgGgEgKAAIgdgBIgHAGgAgNhCQgEACgDAEQgDAEgCAEQgBAFAAAFQAAALAGAHQAHAGALAAQAFAAAFgCQAFgCADgDIAEgIQABgFAAgFQAAgMgGgGQgGgHgLAAQgGAAgFACg");
	this.shape_72.setTransform(937.425,434.675);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AgWA8QgIgCgFgEQgFgFgDgGQgDgHAAgIQAAgKAEgHQAEgHAHgEQAIgEAKgDQALgCANAAIAPAAIAAgJIgBgMQgBgFgDgDQgEgDgFgCQgEgCgIAAQgHAAgGACIgKAEIgIAEIgFACIgCgBIgBgBIgBgDIAAgDIABgFQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAHgEIAJgEIAMgDIAMgBQAMAAAJADQAJADAFAFQAFAFACAIQADAIAAALIAABMIgBACIgDACIgFAAIgFAAIgDgCIgBgCIAAgLQgHAIgJAEQgKAFgJAAQgJAAgHgDgAgFAHQgHABgEADQgEADgCAEQgCAEAAAFQAAAJAFAFQAGAFAKAAQAHAAAIgEQAGgEAIgJIAAgYIgSAAQgIAAgFACg");
	this.shape_73.setTransform(924.75,432.475);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AgbA+IgDgBIgCgBIAAgCIAAhxIAAgCIACgCIACAAIAFgBIAFABIADAAIABACIABACIAAAQIAIgLIAHgGQAEgDAEgBIAHgBIAEAAIAEAAIAEACIADABIABACIAAABIAAACIAAAFIAAAFIAAADIgBACIgCAAIgCAAIgDgCIgFgBIgFgBIgGACIgGAEIgGAIIgIALIAABLIgBACIgCABIgDABIgFAAIgFAAg");
	this.shape_74.setTransform(915.675,432.4);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("Ag2BSQgDAAgDgCQgCgCAAgFIAAiRQAAgFACgCQADgCADAAIAlAAQAVAAAOAGQAPAFAKAKQAKALAFAOQAFAPAAATQAAAUgGAQQgFAQgKAKQgLALgPAFQgPAFgVAAgAgpBAIAXAAQAQAAAKgEQAKgEAIgIQAHgIAEgMQADgNAAgPQAAgOgDgLQgEgMgGgIQgIgIgKgFQgKgFgRAAIgXAAg");
	this.shape_75.setTransform(902.9,430.275);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgdAKQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgBgHIABgHQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAIA6AAIACABIACABIABADIABAEQAAAFgCACQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_76.setTransform(786.35,223.125);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AgUBYQgOgGgKgMQgLgMgEgQQgHgRAAgXQAAgVAHgSQAFgSALgMQAKgNAPgHQAQgGAQAAIAQACIANADIAMAGIAHAEIADAEIABACIAAADIAAAEIAAAFIgBAEIgBACIgDAAQgCAAgDgCIgJgHIgOgGQgIgDgLAAQgNAAgIAFQgLAFgGAJQgHAKgFAOQgDANgBARQABASADANQAEANAHAJQAHAJALAFQAIAEANAAQAMAAAHgCQAJgDAGgEIAJgFQAEgDACAAIACAAIABACIABADIAAAFIAAAFIgBACIgBADIgCACIgGAEIgLAHIgPAEQgJACgKAAQgSAAgOgGg");
	this.shape_77.setTransform(761.4,221.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgNAeQgGgCgFgEQgEgEgDgGQgDgGABgIQAAgGACgGQADgGAFgEQAFgFAGgCQAGgDAHAAQAHAAAGACQAHADAEAEQAEAEADAGQACAGAAAHQAAAGgCAGQgDAGgEAFQgFAFgHACQgGADgHAAQgHAAgGgDgAgFgQIgGAEQgCACgBAEQgCADAAADQAAAEACADQABAEACACIAGAEQACABAEAAQADAAADgBIAFgEQADgDAAgDQACgDAAgEIgCgGQAAgEgDgCIgGgEQgDgBgDAAQgCAAgDABg");
	this.shape_78.setTransform(748.45,214.275);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AgaBbQgLgDgIgFQgHgGgFgJQgEgIAAgLQAAgJADgHQADgHAFgGQAGgGAHgGIASgJIgPgJQgHgFgEgGQgFgFgCgHQgCgGAAgIQAAgKADgIQAEgIAHgHQAHgGALgDQAKgEAOAAQAOAAAKADQAKADAHAGQAGAGADAIQADAIAAAIQAAAIgCAGQgCAHgFAGQgEAGgHAFIgPAKIASAJQAIAFAFAGQAFAGADAHQADAHAAAIQAAAMgEAJQgFAJgIAHQgIAGgLADQgMADgOAAQgOAAgMgDgAgQAQIgLAJQgFAFgCAFQgCAFAAAHQAAANAJAIQAKAHASAAQASAAAJgHQAJgIAAgNQAAgGgCgFQgDgGgEgEQgFgFgIgEIgQgJIgPAIgAgWhDQgIAHAAAMQAAAFACAFQACAFAEAEQAEAEAGAEIAOAJQAOgIAIgJQAHgJAAgKQAAgGgCgFQgCgFgEgDQgEgEgGgBQgGgCgHAAQgOAAgIAHg");
	this.shape_79.setTransform(729.625,221.075);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AAWBcIgEgBIgCgBIgBgCIAAgmIhJAAIgDgBIgCgCIgCgDIAAgGIAAgEIABgEIABgEIACgDIBAhuIACgCIAEgCIAFAAIAHAAIAJAAIAFAAIAEACIABACIAAB0IAUAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAABQACACAAAGQAAAEgCADQAAABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgUAAIAAAmIgBACIgCABIgEABIgGAAIgFAAgAgrAdIA6AAIAAhjg");
	this.shape_80.setTransform(714.875,221.1);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AgLANQgDgDAAgKQAAgJADgDQADgEAIAAQAJAAADAEQADADAAAJQAAAKgDADQgEADgIAAQgIAAgDgDg");
	this.shape_81.setTransform(704.025,228.75);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AAWBcIgEgBIgCgBIgBgCIAAgmIhJAAIgDgBIgCgCIgCgDIAAgGIAAgEIABgEIABgEIACgDIBAhuIACgCIAEgCIAFAAIAHAAIAJAAIAFAAIAEACIABACIAAB0IAUAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAABQACACAAAGQAAAEgCADQAAABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgUAAIAAAmIgBACIgCABIgEABIgGAAIgFAAgAgrAdIA6AAIAAhjg");
	this.shape_82.setTransform(692.925,221.1);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AgdAKQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgBgHIABgHQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAIA6AAIACABIACABIABADIABAEQAAAFgCACQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_83.setTransform(786.35,274.125);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AgUBYQgOgGgKgLQgLgMgEgSQgHgQAAgXQAAgWAHgRQAFgSALgNQAKgMAPgHQAQgGAQAAQAIAAAIACIANADIAMAGIAHAEIADADIABADIAAADIAAAEIAAAFIgBADIgBADIgDAAQgCAAgDgDIgJgGIgOgGQgIgDgLAAQgNAAgIAFQgLAFgGAKQgHAJgFANQgDAOgBARQABASADAMQAEAOAHAJQAHAJALAEQAIAFANAAQAMAAAHgCQAJgDAGgDIAJgHQAEgCACAAIACAAIABACIABADIAAAFIAAAFIgBADIgBACIgCACIgGAFIgLAGIgPAEQgJACgKAAQgSAAgOgGg");
	this.shape_84.setTransform(761.4,272.1);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AgNAeQgGgCgFgEQgEgEgDgGQgDgGABgIQAAgGACgGQADgGAFgEQAFgFAGgCQAGgDAHAAQAHAAAGACQAHADAEAEQAEAEADAGQACAGAAAHQAAAGgCAGQgDAGgEAFQgFAFgHACQgGADgHAAQgHAAgGgDgAgFgQIgGAEQgCACgBAEQgCADAAADQAAAEACADQABAEACACIAGAEQACABAEAAQADAAADgBIAFgEQADgDAAgDQACgDAAgEIgCgGQAAgEgDgCIgGgEQgDgBgDAAQgCAAgDABg");
	this.shape_85.setTransform(748.45,265.275);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AgaBbQgLgDgIgFQgHgGgFgJQgEgIAAgLQAAgJADgHQADgHAFgGQAGgGAHgGIASgJIgPgJQgHgFgEgGQgFgFgCgHQgCgGAAgIQAAgKADgIQAEgIAHgHQAHgGALgDQAKgEAOAAQAOAAAKADQAKADAHAGQAGAGADAIQADAIAAAIQAAAIgCAGQgCAHgFAGQgEAGgHAFIgPAKIASAJQAIAFAFAGQAFAGADAHQADAHAAAIQAAAMgEAJQgFAJgIAHQgIAGgLADQgMADgOAAQgOAAgMgDgAgQAQIgLAJQgFAFgCAFQgCAFAAAHQAAANAJAIQAKAHASAAQASAAAJgHQAJgIAAgNQAAgGgCgFQgDgGgEgEQgFgFgIgEIgQgJIgPAIgAgWhDQgIAHAAAMQAAAFACAFQACAFAEAEQAEAEAGAEIAOAJQAOgIAIgJQAHgJAAgKQAAgGgCgFQgCgFgEgDQgEgEgGgBQgGgCgHAAQgOAAgIAHg");
	this.shape_86.setTransform(729.625,272.075);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AgLANQgDgDAAgKQAAgJADgEQADgDAIABQAJgBADADQADAEAAAJQAAAKgDADQgEAEgIAAQgIAAgDgEg");
	this.shape_87.setTransform(718.725,279.75);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AgXBdIgOgEIgLgEIgFgDIgBgCIgBgCIgBgEIAAgFQAAgFABgCQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAAAAAIAGACIAKAFIANAFQAJACAJAAQAJAAAHgCQAHgCAGgFQAFgEACgGQACgGABgHQAAgIgEgGQgDgHgGgEQgGgFgJgCQgHgDgMAAIgSAAIgCAAIgCgCIgBgDIgBgDIABgFIABgDIABgBIADgBIAQAAQAJAAAHgCQAHgDAGgEQAFgFACgGQADgGAAgIQAAgGgCgFQgCgFgDgEQgEgEgGgCQgGgCgGAAQgIAAgHACIgNAGIgJAFIgEADIgCgBIgCgBIAAgDIgBgFIABgEIAAgDIACgCIACgCIAEgEIALgFQAGgDAIgBQAHgCAKAAQALAAAKADQAKADAGAGQAHAGADAJQADAIAAAKQAAAIgDAIQgCAHgEAGQgFAGgGAEQgGAEgIABIAAABQAJABAIADQAIADAFAGQAGAGADAHQADAIABAIQAAANgFAKQgFAKgHAHQgJAIgMAEQgMADgOAAIgRgBg");
	this.shape_88.setTransform(707.55,272.075);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("AgdAKQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgBgHIABgHQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAIA6AAIACABIACABIABADIABAEQAAAFgCACQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_89.setTransform(786.35,347.825);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AgUBYQgOgGgKgLQgLgMgEgSQgHgQAAgXQAAgVAHgTQAFgRALgNQAKgMAPgHQAQgGAQAAIAQABIANAEIAMAFIAHAFIADADIABADIAAADIAAAEIAAAFIgBADIgBADIgDAAQgCAAgDgDIgJgGIgOgGQgIgDgLAAQgNAAgIAFQgLAFgGAKQgHAJgFANQgDAOgBARQABASADAMQAEAOAHAJQAHAJALAEQAIAFANAAQAMAAAHgDQAJgCAGgDIAJgHQAEgCACAAIACABIABABIABADIAAAGIAAADIgBAEIgBACIgCACIgGAFIgLAFIgPAFQgJACgKAAQgSAAgOgGg");
	this.shape_90.setTransform(761.4,345.8);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AgNAeQgGgCgFgEQgEgEgDgGQgDgGABgIQAAgGACgGQADgGAFgEQAFgFAGgCQAGgDAHAAQAHAAAGACQAHADAEAEQAEAEADAGQACAGAAAHQAAAGgCAGQgDAGgEAFQgFAFgHACQgGADgHAAQgHAAgGgDgAgFgQIgGAEQgCACgBAEQgCADAAADQAAAEACADQABAEACACIAGAEQACABAEAAQADAAADgBIAFgEQADgDAAgDQACgDAAgEIgCgGQAAgEgDgCIgGgEQgDgBgDAAQgCAAgDABg");
	this.shape_91.setTransform(748.45,338.975);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("AgeBYQgMgGgHgMQgHgMgDgRQgEgSABgWQgBgUAEgSQADgRAIgNQAIgMAMgHQANgHARAAQARAAAMAGQAMAGAHAMQAHAMADASQAEARAAAWQgBAVgDARQgDASgIAMQgIANgMAHQgMAGgSAAQgRAAgMgGgAgShEQgHAGgFAKQgFAKgBANQgCAOAAAPQAAATADAPQACAOAEAJQAFAJAIAEQAGAEAKAAQAHAAAGgCQAHgDAEgEQAEgFADgHQADgGACgIIACgSIABgUIgBgXIgDgTQgDgJgDgGQgCgGgFgEQgEgEgGgBQgFgCgGAAQgLAAgIAFg");
	this.shape_92.setTransform(729.65,345.775);

	this.drg = new lib.dragger();
	this.drg.name = "drg";
	this.drg.setTransform(885.3,388.25,1,1,0,0,0,47.2,0);

	this.instance = new lib.thermometer();
	this.instance.setTransform(819.55,323.35);

	this.i_2 = new lib.ice_melts();
	this.i_2.name = "i_2";
	this.i_2.setTransform(555.1,358.75,1.3968,1.3968,0,0,0,52.1,43.4);
	this.i_2.alpha = 0.6992;

	this.i_0 = new lib.ice_melts();
	this.i_0.name = "i_0";
	this.i_0.setTransform(145.2,358.75,1.3968,1.3968,0,0,0,52.1,43.4);
	this.i_0.alpha = 0.6992;

	this.i_1 = new lib.ice_melts();
	this.i_1.name = "i_1";
	this.i_1.setTransform(350.15,358.75,1.3968,1.3968,0,0,0,52.1,43.4);
	this.i_1.alpha = 0.6992;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.i_1},{t:this.i_0},{t:this.i_2},{t:this.instance},{t:this.drg},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_4
	this.blc = new lib.blocker();
	this.blc.name = "blc";
	this.blc.setTransform(819.9,388.25);

	this.timeline.addTween(cjs.Tween.get(this.blc).wait(1));

	// Layer_3
	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FF0000").s().p("AjdenQhchcAAiCQAAiCBchcQA2g2BDgWMAAAg2hIDJAAMAAAA2hQBDAWA2A2QBcBcAACCQAACChcBcQhcBciCAAQiBAAhchcg");
	this.shape_93.setTransform(819.35,328.475);

	this.timeline.addTween(cjs.Tween.get(this.shape_93).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(559.7,317.1,497.5,246.89999999999998);
// library properties:
lib.properties = {
	id: '53BBB82D4827AD4C8B0BCEF016BE5337',
	width: 1072,
	height: 603,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['53BBB82D4827AD4C8B0BCEF016BE5337'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;